/**28-02-2021*/
/** USER_DETAILS DATABASE CREATE SCRIPT */
CREATE TABLE USER_DETAILS (USER_NAME VARCHAR(255), PASSWORD VARCHAR(255), MAIL_ID VARCHAR(255), STATUS VARCHAR(255), CREATED_DATE DATE);

/** OTP_DETAILS DATABASE CREATE SCRIPT */
CREATE TABLE OTP_DETAILS (MAIL_ID VARCHAR(255), OTP NUMBER(10), STATUS VARCHAR(255), CREATED_DATE DATE, EXPIRED_DATE DATE);


COMMIT;