package woof.project.Entity;

import javax.persistence.*;

import org.springframework.context.annotation.Configuration;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Configuration

@DynamoDBTable(tableName = "User_Pro_Doc")
public class DatabaseFile {
	
	@DynamoDBAttribute
	private String fileName;

	@DynamoDBAttribute
	private String fileType;

	@Lob
	private byte[] data;
	
	public DatabaseFile() {

	}

	
	public DatabaseFile(String fileName, String fileType,byte[] data) {
		this.fileName = fileName;
		this.fileType = fileType;
		//this.phone = phone;
		this.data = data;
	}


	

	public String getFileName() {
		return fileName;
	}


	public void setFileName(String fileName) {
		this.fileName = fileName;
	}


	public String getFileType() {
		return fileType;
	}


	public void setFileType(String fileType) {
		this.fileType = fileType;
	}


	public byte[] getData() {
		return data;
	}


	public void setData(byte[] data) {
		this.data = data;
	}

	}
